### ISSUE TITLE
it's not working with newer versions of node.js

### ISSUE THREAD

**Issue by loxs** [mwild1/xmppjs#1]

**Comment by DTrejo** [comment]
In specific, my error is this:

<code>Error: Cannot find module './node-xml/lib/node-xml'</code>

Now I'm off to clone that project.

Now that I've cloned it, I get

<pre>DTrejo:xmppjs david$ node examples/echo.js 
The 'sys' module is now called 'util'. It should have a similar interface.
The 'tcp' module is now called 'net'. Otherwise it should have a similar interface.
New connection status: 1
CONNECTED.
SND: <stream:stream xmlns='jabber:component:accept' xmlns:stream='http://etherx.jabber.org/streams' to='echo.localhost'>
RCV: <?xml version='1.0'?><stream:stream id='' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xmlns='jabber:component:accept'><stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>echo.localhost does not match any configured external components</text></stream:error></stream:stream>
STREAM: opened.
New connection status: 3
Calculated authentication token 0b156215b189103c3d268f61299a854cd0b31e70 from stream id '' and password 'hellohello'
Sending authentication token...
SND: <handshake>0b156215b189103c3d268f61299a854cd0b31e70</handshake>
STANZA: <error xmlns='http://etherx.jabber.org/streams'><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>echo.localhost does not match any configured external components</text></error>
STREAM: closed.

/Dropbox/dev/nxmpp/xmppjs/xmpp.js:276
        this.socket.close();
              ^
TypeError: Object #<a Stream> has no method 'close'
    at Object._stream_closed (/Dropbox/dev/nxmpp/xmppjs/xmpp.js:276:15)
    at Object.closed (/Dropbox/dev/nxmpp/xmppjs/xmpp.js:17:71)
    at [object Object].onEndElementNS (/Dropbox/dev/nxmpp/xmppjs/xmpp.js:94:15)
    at [object Object]._fireEvent (/Dropbox/dev/nxmpp/xmppjs/node-xml/lib/node-xml.js:953:21)
    at [object Object]._parseLoop (/Dropbox/dev/nxmpp/xmppjs/node-xml/lib/node-xml.js:986:18)
    at Timer.callback (/Dropbox/dev/nxmpp/xmppjs/node-xml/lib/node-xml.js:823:18)
    at node.js:634:9
</pre>


(This is with the prosody server running, based on the instructions at http://prosody.im/ and http://xmppjs.prosody.im/). By the way, I am running Snow Leopard.

**Comment by tensiondriven** [comment]
Is this because "echo.localhost" should be a jabber id in the format "user@domain.com"?

(Note that when I specify a 'jid in the format username@domain.com, I get the same error.)

**Comment by vikrambodicherla** [comment]
Any updates on this?

**Comment by mwild1** [comment]
Sorry, not from me. I'm afraid that I have neither the time nor motivation for continued development on xmpp.js. Since I started the project other Node XMPP libraries have become available, from people with more time to put into the matter - such as node-xmpp. I recommend taking a look at those if you can.

I'm happy to give up the project to a good home, just let me know if you're interested in taking it on. If someone does this, I would love to see the project continued along the same lines as it was started - small, simple, and solving a one specific problem (using Node as an XMPP server component). I personally don't see any purpose in "competing" with the other available XMPP libraries, which try to encompass everything possible in XMPP. But hey, it's open-source for a reason... do whatever you want :)

**Comment by mwild1** [comment]
Thanks to @sammy44nts whose pull request I just merged, I think we can close this issue :)
